name: Deploy AWS Lambda

on:
  push:
    branches:
      - main  # 💡 AJUSTE: Mantenha 'main' ou altere para a branch principal que dispara o deploy.
    paths:
      - 'TesteCloud/**' # 💡 AJUSTE: Use o diretório completo para consistência.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Criar o arquivo ZIP do código
      - name: Zip Lambda code
        run: |
          # Navega para a pasta do código.
          # Cria um ZIP que contém APENAS o conteúdo da pasta, não a pasta TesteCloud em si.
          zip -r deployment-package.zip .
        working-directory: ./TesteCloud # 💡 AJUSTE: Usando o diretório correto
      
      # 2. Configurar Credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # 💡 AJUSTE: Mude para a sua região

      # 3. Deploy da Função Lambda
      # A ação aws-lambda-deploy irá pegar o ZIP e enviar para a função.
      - name: Deploy Lambda function
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: slackBotTests # ⚠️ Mude para o NOME EXATO da sua função na AWS
          zip-file: ./TesteCloud/deployment-package.zip # Caminho para o arquivo ZIP
          # handler: script.lambda_handler # Opcional: Se quiser garantir o handler